name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Build and push Docker image
        run: |
          echo "Iniciando a construção da imagem Docker"
          docker build -t dummy-server:latest .
          echo "Construção da imagem concluída"
          
          echo "Marcando a imagem Docker"
          docker tag dummy-server:latest ${{ secrets.DOCKER_REPO_URL }}/dummy-server:latest
          echo "Marcação da imagem concluída"
        
          echo "Fazendo login no Docker Hub"
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          echo "Login no Docker Hub concluído"
        
          echo "Enviando a imagem Docker para o Docker Hub"
          docker push ${{ secrets.DOCKER_REPO_URL }}/dummy-server:latest
          echo "Envio da imagem concluído"
      - name: SSH into EC2 instance and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.MY_EC2_SSH_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_REPO_URL }}/dummy-server:latest
            sudo docker stop my-node-app || true
            sudo docker rm my-node-app || true
            sudo docker run -d -p 3000:3000 --name my-node-app ${{ secrets.DOCKER_REPO_URL }}/dummy-server:latest